# Generated by Django 2.0 on 2019-04-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WH_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsorder',
            name='person_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodsorder',
            name='which_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goodsorder',
            name='which_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
