# Generated by Django 2.0 on 2019-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WH_order', '0002_auto_20190412_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsorder',
            name='isdeal',
            field=models.SmallIntegerField(default=0),
        ),
    ]
