# Generated by Django 2.0 on 2019-04-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WH_order', '0003_goodsorder_isdeal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsorder',
            options={'ordering': ['pub_time']},
        ),
    ]
