# Generated by Django 2.0 on 2019-04-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WH_share', '0002_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_time']},
        ),
    ]
