# Generated by Django 2.0 on 2019-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WH_scene', '0002_scenes_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenes',
            name='scene_desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
