# Generated by Django 2.0 on 2019-04-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WH_scene', '0003_scenes_scene_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenes',
            options={'ordering': ['ranking']},
        ),
    ]
