# Generated by Django 2.0 on 2019-04-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WH_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['sales']},
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='seals',
            new_name='sales',
        ),
    ]
